name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag smileproject/faasprocessing:$(date +%s)
    - uses: actions/checkout@v2
    - name: Push the docker image
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_KEY }} && docker push  smileproject/faasprocessing
